apiVersion: apps/v1
kind: Deployment
metadata:
  name: kch-database-deployment
  namespace: np-kch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: counter-database