apiVersion: apps/v1
kind: Deployment
metadata:
  name: kch-server-deployment
  namespace: np-kch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: dockerman75/server-count-kch